<?php session_start(); require_once __DIR__ . '/../config/db.php'; requireLogin(['patient']);
$p=$pdo->prepare('SELECT id FROM patients WHERE user_id=? LIMIT 1'); $p->execute([$_SESSION['user_id']]); $patientId=(int)$p->fetchColumn();
if($_SERVER['REQUEST_METHOD']==='POST'){ $pdo->prepare('INSERT INTO appointments (patient_id,doctor_id,appointment_date,appointment_time,status,symptoms,notes) VALUES (?,?,?,?,?,?,?)')->execute([$patientId,(int)$_POST['doctor_id'],$_POST['appointment_date'],$_POST['appointment_time'],'pending',trim($_POST['symptoms']),'']); setFlash('success','Appointment booked with pending status.'); redirectTo('/patient/book-appointment.php');}
$f=trim($_GET['specialization']??''); $sql='SELECT d.id,d.specialization,d.fee,u.name FROM doctors d JOIN users u ON u.id=d.user_id'; $pr=[]; if($f!==''){ $sql.=' WHERE d.specialization LIKE ?'; $pr[]="%$f%";} $sql.=' ORDER BY u.name'; $s=$pdo->prepare($sql); $s->execute($pr); $doctors=$s->fetchAll();
$pageTitle='Book Appointment'; include __DIR__ . '/../includes/header.php'; ?>
<h2 class="fw-bold mb-3">Book Appointment</h2>
<form class="row g-2 mb-3"><div class="col-md-4"><input class="form-control" name="specialization" value="<?= e($f) ?>" placeholder="Filter specialization"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div></form>
<div class="card p-3"><form method="POST" class="row g-3"><div class="col-md-6"><label class="form-label">Doctor</label><select class="form-select" name="doctor_id" required><option value="">Select doctor</option><?php foreach($doctors as $d): ?><option value="<?= e((string)$d['id']) ?>"><?= e($d['name']) ?> - <?= e($d['specialization']) ?> (PKR <?= e(number_format((float)$d['fee'],0)) ?>)</option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Date</label><input type="date" class="form-control" name="appointment_date" min="<?= date('Y-m-d') ?>" required></div><div class="col-md-3"><label class="form-label">Time</label><input type="time" class="form-control" name="appointment_time" required></div><div class="col-12"><label class="form-label">Symptoms</label><textarea class="form-control" name="symptoms" required></textarea></div><div class="col-12"><button class="btn btn-primary">Submit Booking</button></div></form></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
