<?php session_start(); require_once __DIR__ . '/../config/db.php'; requireLogin(['patient']);
$p=$pdo->prepare('SELECT id FROM patients WHERE user_id=? LIMIT 1'); $p->execute([$_SESSION['user_id']]); $patientId=(int)$p->fetchColumn();
$s=$pdo->prepare("SELECT COUNT(*) FROM appointments WHERE patient_id=? AND appointment_date>=CURDATE() AND status IN ('pending','confirmed')"); $s->execute([$patientId]); $up=(int)$s->fetchColumn();
$s=$pdo->prepare("SELECT COUNT(*) FROM appointments WHERE patient_id=? AND status='completed'"); $s->execute([$patientId]); $past=(int)$s->fetchColumn();
$s=$pdo->prepare("SELECT a.*,u.name doctor_name,d.specialization FROM appointments a JOIN doctors d ON d.id=a.doctor_id JOIN users u ON u.id=d.user_id WHERE a.patient_id=? ORDER BY a.appointment_date DESC"); $s->execute([$patientId]); $rows=$s->fetchAll();
$pageTitle='Patient Dashboard'; include __DIR__ . '/../includes/header.php'; ?>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="fw-bold mb-0">Patient Dashboard</h2><a class="btn btn-primary" href="<?= $baseUrl ?>/patient/book-appointment.php">Quick Book</a></div>
<div class="row g-3 mb-3"><div class="col-md-6"><div class="card p-3"><small class="text-muted">Upcoming Appointments</small><h3 class="fw-bold mb-0"><?= e((string)$up) ?></h3></div></div><div class="col-md-6"><div class="card p-3"><small class="text-muted">Past Appointments</small><h3 class="fw-bold mb-0"><?= e((string)$past) ?></h3></div></div></div>
<div class="table-wrap"><div class="table-responsive"><table class="table table-striped table-hover mb-0"><thead><tr><th>Doctor</th><th>Specialization</th><th>Date</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['doctor_name']) ?></td><td><?= e($r['specialization']) ?></td><td><?= e($r['appointment_date']) ?> <?= e(substr($r['appointment_time'],0,5)) ?></td><td><?= e(ucfirst($r['status'])) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
