<?php session_start(); require_once __DIR__ . '/../config/db.php'; requireLogin(['admin']);
if($_SERVER['REQUEST_METHOD']==='POST'){ $pdo->prepare('UPDATE appointments SET status=?,notes=? WHERE id=?')->execute([trim($_POST['status']),trim($_POST['notes']), (int)$_POST['appointment_id']]); setFlash('success','Appointment updated.'); redirectTo('/admin/appointments.php');}
$status=trim($_GET['status']??''); $date=trim($_GET['date']??''); $doctor=(int)($_GET['doctor_id']??0);
$sql="SELECT a.*,u1.name patient_name,u2.name doctor_name FROM appointments a JOIN patients p ON p.id=a.patient_id JOIN users u1 ON u1.id=p.user_id JOIN doctors d ON d.id=a.doctor_id JOIN users u2 ON u2.id=d.user_id WHERE 1=1"; $params=[];
if($status!==''){ $sql.=' AND a.status=?'; $params[]=$status;} if($date!==''){ $sql.=' AND a.appointment_date=?'; $params[]=$date;} if($doctor>0){ $sql.=' AND a.doctor_id=?'; $params[]=$doctor;} $sql.=' ORDER BY a.appointment_date DESC'; $st=$pdo->prepare($sql); $st->execute($params); $rows=$st->fetchAll();
$docs=$pdo->query('SELECT d.id,u.name FROM doctors d JOIN users u ON u.id=d.user_id ORDER BY u.name')->fetchAll(); $pageTitle='Appointments'; include __DIR__ . '/../includes/header.php'; ?>
<h2 class="fw-bold mb-3">Appointments</h2>
<form class="row g-2 mb-3"><div class="col-md-3"><select class="form-select" name="status"><option value="">All Status</option><?php foreach(['pending','confirmed','cancelled','completed'] as $s): ?><option value="<?= $s ?>" <?= $status===$s?'selected':'' ?>><?= ucfirst($s) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><input type="date" class="form-control" name="date" value="<?= e($date) ?>"></div><div class="col-md-3"><select class="form-select" name="doctor_id"><option value="">All Doctors</option><?php foreach($docs as $d): ?><option value="<?= e((string)$d['id']) ?>" <?= $doctor===(int)$d['id']?'selected':'' ?>><?= e($d['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Apply</button></div></form>
<div class="table-wrap"><div class="table-responsive"><table class="table table-striped table-hover mb-0"><thead><tr><th>Patient</th><th>Doctor</th><th>Date</th><th>Status</th><th>Symptoms</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['patient_name']) ?></td><td><?= e($r['doctor_name']) ?></td><td><?= e($r['appointment_date']) ?> <?= e(substr($r['appointment_time'],0,5)) ?></td><td><?= e(ucfirst($r['status'])) ?></td><td><?= e($r['symptoms']) ?></td><td><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#a<?= e((string)$r['id']) ?>">Status</button></td></tr><div class="modal fade" id="a<?= e((string)$r['id']) ?>" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST"><div class="modal-header"><h5 class="modal-title">Update Appointment</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="appointment_id" value="<?= e((string)$r['id']) ?>"><select class="form-select mb-2" name="status"><?php foreach(['pending','confirmed','cancelled','completed'] as $s): ?><option value="<?= $s ?>" <?= $r['status']===$s?'selected':'' ?>><?= ucfirst($s) ?></option><?php endforeach; ?></select><textarea class="form-control" name="notes" placeholder="Notes"><?= e($r['notes']) ?></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div></div><?php endforeach; ?></tbody></table></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
