<?php session_start(); require_once __DIR__ . '/../config/db.php'; requireLogin(['admin']);
if($_SERVER['REQUEST_METHOD']==='POST'){ $a=$_POST['action']??'';
if($a==='delete'){ $pdo->prepare('DELETE FROM doctors WHERE id=?')->execute([(int)$_POST['doctor_id']]); setFlash('success','Doctor deleted.'); redirectTo('/admin/doctors.php');}
if($a==='edit'){ $pdo->prepare('UPDATE doctors SET specialization=?,qualification=?,experience_years=?,fee=?,available_days=?,bio=? WHERE id=?')->execute([trim($_POST['specialization']),trim($_POST['qualification']),(int)$_POST['experience_years'],(float)$_POST['fee'],trim($_POST['available_days']),trim($_POST['bio']),(int)$_POST['doctor_id']]); setFlash('success','Doctor updated.'); redirectTo('/admin/doctors.php');}
if($a==='add'){ $pdo->beginTransaction(); try{$pdo->prepare('INSERT INTO users (name,email,password,role,phone) VALUES (?,?,?,"doctor",?)')->execute([trim($_POST['name']),trim($_POST['email']),password_hash($_POST['password'],PASSWORD_DEFAULT),trim($_POST['phone'])]); $uid=(int)$pdo->lastInsertId(); $pdo->prepare('INSERT INTO doctors (user_id,specialization,qualification,experience_years,fee,available_days,bio,profile_pic) VALUES (?,?,?,?,?,?,?,"")')->execute([$uid,trim($_POST['specialization']),trim($_POST['qualification']), (int)$_POST['experience_years'], (float)$_POST['fee'], trim($_POST['available_days']), trim($_POST['bio'])]); $pdo->commit(); setFlash('success','Doctor added.'); }catch(Throwable $e){$pdo->rollBack(); setFlash('danger','Add failed.');} redirectTo('/admin/doctors.php');}}
$q=trim($_GET['specialization']??''); $sql='SELECT d.*,u.name,u.phone FROM doctors d JOIN users u ON u.id=d.user_id'; $p=[]; if($q!==''){ $sql.=' WHERE d.specialization LIKE ?'; $p[]="%$q%";} $sql.=' ORDER BY d.id DESC'; $s=$pdo->prepare($sql); $s->execute($p); $rows=$s->fetchAll();
$pageTitle='Doctors'; include __DIR__ . '/../includes/header.php'; ?>
<div class="d-flex justify-content-between mb-3"><h2 class="fw-bold">Doctors</h2><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add">Add Doctor</button></div>
<form class="row g-2 mb-3"><div class="col-md-4"><input class="form-control" name="specialization" value="<?= e($q) ?>" placeholder="Filter specialization"></div><div class="col-auto"><button class="btn btn-outline-primary">Filter</button></div></form>
<div class="table-wrap"><div class="table-responsive"><table class="table table-striped table-hover mb-0"><thead><tr><th>Name</th><th>Specialization</th><th>Fee</th><th>Phone</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['name']) ?></td><td><?= e($r['specialization']) ?></td><td>PKR <?= e(number_format((float)$r['fee'],0)) ?></td><td><?= e($r['phone']) ?></td><td><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#e<?= e((string)$r['id']) ?>">Edit</button> <form method="POST" class="d-inline"><input type="hidden" name="action" value="delete"><input type="hidden" name="doctor_id" value="<?= e((string)$r['id']) ?>"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Delete doctor?')">Delete</button></form></td></tr>
<div class="modal fade" id="e<?= e((string)$r['id']) ?>" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST"><div class="modal-header"><h5 class="modal-title">Edit Doctor</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="action" value="edit"><input type="hidden" name="doctor_id" value="<?= e((string)$r['id']) ?>"><input class="form-control mb-2" name="specialization" value="<?= e($r['specialization']) ?>" placeholder="Specialization"><input class="form-control mb-2" name="qualification" value="<?= e($r['qualification']) ?>" placeholder="Qualification"><input class="form-control mb-2" type="number" name="experience_years" value="<?= e((string)$r['experience_years']) ?>" placeholder="Experience"><input class="form-control mb-2" type="number" step="0.01" name="fee" value="<?= e((string)$r['fee']) ?>" placeholder="Fee"><input class="form-control mb-2" name="available_days" value="<?= e($r['available_days']) ?>" placeholder="Available days"><textarea class="form-control" name="bio" placeholder="Bio"><?= e($r['bio']) ?></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div></div>
<?php endforeach; ?></tbody></table></div></div>
<div class="modal fade" id="add" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST"><div class="modal-header"><h5 class="modal-title">Add Doctor</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><input type="hidden" name="action" value="add"><div class="col-md-6"><input class="form-control" name="name" placeholder="Name" required></div><div class="col-md-6"><input class="form-control" type="email" name="email" placeholder="Email" required></div><div class="col-md-6"><input class="form-control" name="phone" placeholder="Phone" required></div><div class="col-md-6"><input class="form-control" type="password" name="password" placeholder="Password" required></div><div class="col-md-6"><input class="form-control" name="specialization" placeholder="Specialization" required></div><div class="col-md-6"><input class="form-control" name="qualification" placeholder="Qualification"></div><div class="col-md-4"><input class="form-control" type="number" name="experience_years" placeholder="Experience"></div><div class="col-md-4"><input class="form-control" type="number" step="0.01" name="fee" placeholder="Fee"></div><div class="col-md-4"><input class="form-control" name="available_days" placeholder="Available days"></div><div class="col-12"><textarea class="form-control" name="bio" placeholder="Bio"></textarea></div></div><div class="modal-footer"><button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save</button></div></form></div></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
