<?php session_start(); require_once __DIR__ . '/../config/db.php'; requireLogin(['admin']);
if($_SERVER['REQUEST_METHOD']==='POST'){ $a=$_POST['action']??''; if($a==='delete'){ $pdo->prepare('DELETE FROM patients WHERE id=?')->execute([(int)$_POST['patient_id']]); setFlash('success','Patient deleted.'); redirectTo('/admin/patients.php');} if($a==='edit'){ $pdo->prepare('UPDATE patients SET age=?,gender=?,blood_group=?,address=?,emergency_contact=? WHERE id=?')->execute([(int)$_POST['age'],trim($_POST['gender']),trim($_POST['blood_group']),trim($_POST['address']),trim($_POST['emergency_contact']),(int)$_POST['patient_id']]); setFlash('success','Patient updated.'); redirectTo('/admin/patients.php');} if($a==='add'){ $pdo->beginTransaction(); try{$pdo->prepare('INSERT INTO users (name,email,password,role,phone) VALUES (?,?,?,"patient",?)')->execute([trim($_POST['name']),trim($_POST['email']),password_hash($_POST['password'],PASSWORD_DEFAULT),trim($_POST['phone'])]); $uid=(int)$pdo->lastInsertId(); $pdo->prepare('INSERT INTO patients (user_id,age,gender,blood_group,address,emergency_contact) VALUES (?,?,?,?,?,?)')->execute([$uid,(int)$_POST['age'],trim($_POST['gender']),trim($_POST['blood_group']),trim($_POST['address']),trim($_POST['emergency_contact'])]); $pdo->commit(); setFlash('success','Patient added.'); }catch(Throwable $e){$pdo->rollBack(); setFlash('danger','Add failed.');} redirectTo('/admin/patients.php');}}
$q=trim($_GET['name']??''); $sql='SELECT p.*,u.name,u.phone FROM patients p JOIN users u ON u.id=p.user_id'; $p=[]; if($q!==''){ $sql.=' WHERE u.name LIKE ?'; $p[]="%$q%";} $sql.=' ORDER BY p.id DESC'; $s=$pdo->prepare($sql); $s->execute($p); $rows=$s->fetchAll();
$pageTitle='Patients'; include __DIR__ . '/../includes/header.php'; ?>
<div class="d-flex justify-content-between mb-3"><h2 class="fw-bold mb-0">Patients</h2><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPatient">Add Patient</button></div>
<form class="row g-2 mb-3"><div class="col-md-4"><input class="form-control" name="name" value="<?= e($q) ?>" placeholder="Search name"></div><div class="col-auto"><button class="btn btn-outline-primary">Search</button></div></form>
<div class="table-wrap"><div class="table-responsive"><table class="table table-striped table-hover mb-0"><thead><tr><th>Name</th><th>Age</th><th>Blood Group</th><th>Phone</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['name']) ?></td><td><?= e((string)$r['age']) ?></td><td><?= e($r['blood_group']) ?></td><td><?= e($r['phone']) ?></td><td><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#p<?= e((string)$r['id']) ?>">Edit</button> <form method="POST" class="d-inline"><input type="hidden" name="action" value="delete"><input type="hidden" name="patient_id" value="<?= e((string)$r['id']) ?>"><button class="btn btn-sm btn-outline-danger" onclick="return confirm('Delete patient?')">Delete</button></form></td></tr>
<div class="modal fade" id="p<?= e((string)$r['id']) ?>" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST"><div class="modal-header"><h5 class="modal-title">Edit Patient</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="action" value="edit"><input type="hidden" name="patient_id" value="<?= e((string)$r['id']) ?>"><input class="form-control mb-2" type="number" name="age" value="<?= e((string)$r['age']) ?>" placeholder="Age"><input class="form-control mb-2" name="gender" value="<?= e($r['gender']) ?>" placeholder="Gender"><input class="form-control mb-2" name="blood_group" value="<?= e($r['blood_group']) ?>" placeholder="Blood Group"><textarea class="form-control mb-2" name="address" placeholder="Address"><?= e($r['address']) ?></textarea><input class="form-control" name="emergency_contact" value="<?= e($r['emergency_contact']) ?>" placeholder="Emergency contact"></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div></div>
<?php endforeach; ?></tbody></table></div></div>
<div class="modal fade" id="addPatient" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST"><div class="modal-header"><h5 class="modal-title">Add Patient</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><input type="hidden" name="action" value="add"><div class="col-md-6"><input class="form-control" name="name" placeholder="Name" required></div><div class="col-md-6"><input class="form-control" type="email" name="email" placeholder="Email" required></div><div class="col-md-6"><input class="form-control" name="phone" placeholder="Phone" required></div><div class="col-md-6"><input class="form-control" type="password" name="password" placeholder="Password" required></div><div class="col-md-4"><input class="form-control" type="number" name="age" placeholder="Age"></div><div class="col-md-4"><input class="form-control" name="gender" placeholder="Gender"></div><div class="col-md-4"><input class="form-control" name="blood_group" placeholder="Blood Group"></div><div class="col-md-6"><textarea class="form-control" name="address" placeholder="Address"></textarea></div><div class="col-md-6"><input class="form-control" name="emergency_contact" placeholder="Emergency contact"></div></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
