<?php session_start(); require_once __DIR__ . '/../config/db.php'; requireLogin(['doctor']);
$d=$pdo->prepare('SELECT id FROM doctors WHERE user_id=? LIMIT 1'); $d->execute([$_SESSION['user_id']]); $doctorId=(int)$d->fetchColumn();
if($_SERVER['REQUEST_METHOD']==='POST'){ $pdo->prepare('UPDATE appointments SET status=?,notes=? WHERE id=? AND doctor_id=?')->execute([trim($_POST['status']),trim($_POST['notes']), (int)$_POST['appointment_id'], $doctorId]); setFlash('success','Status updated.'); redirectTo('/doctor/appointments.php');}
$date=trim($_GET['date']??''); $status=trim($_GET['status']??'');
$sql="SELECT a.*,u.name patient_name FROM appointments a JOIN patients p ON p.id=a.patient_id JOIN users u ON u.id=p.user_id WHERE a.doctor_id=?"; $params=[$doctorId];
if($date!==''){ $sql.=' AND a.appointment_date=?'; $params[]=$date;} if($status!==''){ $sql.=' AND a.status=?'; $params[]=$status;} $sql.=' ORDER BY a.appointment_date DESC';
$s=$pdo->prepare($sql); $s->execute($params); $rows=$s->fetchAll();
$pageTitle='Doctor Appointments'; include __DIR__ . '/../includes/header.php'; ?>
<h2 class="fw-bold mb-3">My Appointments</h2>
<form class="row g-2 mb-3"><div class="col-md-3"><input type="date" class="form-control" name="date" value="<?= e($date) ?>"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All Status</option><?php foreach(['pending','confirmed','cancelled','completed'] as $st): ?><option value="<?= $st ?>" <?= $status===$st?'selected':'' ?>><?= ucfirst($st) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div></form>
<div class="table-wrap"><div class="table-responsive"><table class="table table-striped table-hover mb-0"><thead><tr><th>Patient</th><th>Date</th><th>Status</th><th>Symptoms</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['patient_name']) ?></td><td><?= e($r['appointment_date']) ?> <?= e(substr($r['appointment_time'],0,5)) ?></td><td><?= e(ucfirst($r['status'])) ?></td><td><?= e($r['symptoms']) ?></td><td><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#d<?= e((string)$r['id']) ?>">Update</button></td></tr><div class="modal fade" id="d<?= e((string)$r['id']) ?>" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST"><div class="modal-header"><h5 class="modal-title">Update</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="appointment_id" value="<?= e((string)$r['id']) ?>"><select class="form-select mb-2" name="status"><?php foreach(['pending','confirmed','cancelled','completed'] as $st): ?><option value="<?= $st ?>" <?= $r['status']===$st?'selected':'' ?>><?= ucfirst($st) ?></option><?php endforeach; ?></select><textarea class="form-control" name="notes"><?= e($r['notes']) ?></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div></div><?php endforeach; ?></tbody></table></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
