<?php session_start(); require_once __DIR__ . '/../config/db.php'; requireLogin(['doctor']);
$d=$pdo->prepare('SELECT id FROM doctors WHERE user_id=? LIMIT 1'); $d->execute([$_SESSION['user_id']]); $doctorId=(int)$d->fetchColumn();
if($_SERVER['REQUEST_METHOD']==='POST'){ $pdo->prepare('INSERT INTO prescriptions (appointment_id,doctor_id,patient_id,medicines,instructions) VALUES (?,?,?,?,?)')->execute([(int)$_POST['appointment_id'],$doctorId,(int)$_POST['patient_id'],trim($_POST['medicines']),trim($_POST['instructions'])]); setFlash('success','Prescription saved.'); redirectTo('/doctor/prescriptions.php');}
$ap=$pdo->prepare("SELECT a.id,a.patient_id,a.appointment_date,u.name patient_name FROM appointments a JOIN patients p ON p.id=a.patient_id JOIN users u ON u.id=p.user_id WHERE a.doctor_id=? ORDER BY a.appointment_date DESC"); $ap->execute([$doctorId]); $appointments=$ap->fetchAll();
$ls=$pdo->prepare("SELECT pr.*,u.name patient_name,a.appointment_date FROM prescriptions pr JOIN patients p ON p.id=pr.patient_id JOIN users u ON u.id=p.user_id JOIN appointments a ON a.id=pr.appointment_id WHERE pr.doctor_id=? ORDER BY pr.created_at DESC"); $ls->execute([$doctorId]); $rows=$ls->fetchAll();
$pageTitle='Prescriptions'; include __DIR__ . '/../includes/header.php'; ?>
<div class="row g-3"><div class="col-lg-5"><div class="card p-3"><h5>Write Prescription</h5><form method="POST"><div class="mb-2"><select class="form-select" name="appointment_id" id="appointment_id" required><option value="">Select appointment</option><?php foreach($appointments as $a): ?><option value="<?= e((string)$a['id']) ?>" data-patient="<?= e((string)$a['patient_id']) ?>">#<?= e((string)$a['id']) ?> - <?= e($a['patient_name']) ?> (<?= e($a['appointment_date']) ?>)</option><?php endforeach; ?></select></div><input type="hidden" name="patient_id" id="patient_id"><div class="mb-2"><textarea class="form-control" name="medicines" placeholder="Medicines" required></textarea></div><div class="mb-2"><textarea class="form-control" name="instructions" placeholder="Instructions" required></textarea></div><button class="btn btn-primary w-100">Save</button></form></div></div>
<div class="col-lg-7"><div class="table-wrap"><div class="table-responsive"><table class="table table-striped table-hover mb-0"><thead><tr><th>Patient</th><th>Date</th><th>Medicines</th><th>Instructions</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['patient_name']) ?></td><td><?= e($r['appointment_date']) ?></td><td><?= e($r['medicines']) ?></td><td><?= e($r['instructions']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<script>document.getElementById('appointment_id').addEventListener('change',function(){document.getElementById('patient_id').value=this.options[this.selectedIndex].getAttribute('data-patient')||'';});</script>
<?php include __DIR__ . '/../includes/footer.php'; ?>
